export const ROUTES = {
  HOME: '/',
  TOPICS: '/topics',
  TAGS: '/tags',
  LEVELS: '/levels',
};

export const LABELS = {
  TITLE: 'JS, TS, React Cheat Sheets Series',
  HEADER: 'Cheat Sheets',
  HOME: 'Welcome!',
  ABOUT: 'About',
  LEVEL: 'Difficulty',
  LEVELS: 'Explore by Difficulty',
  TAGS: 'Tags',
  TAG: 'Tag',
  TOPICS: 'Topics',
  TOPIC: 'Topic',
  POST: 'Post',
  POSTS: 'Posts',
  RECENT: 'Recently published',
  SEE_TOPICS: 'See all topics',
  FEATURED: 'Featured',
  EXPLORE_TOPICS: 'Explore by Topics',
  BACK_TO_LEVELS: 'See all levels',
  BACK_TO_TAGS: 'See all tags',
  BACK_TO_TOPICS: 'See all topics',
  ALL_TOPICS: 'All topics',
  ALL_LEVELS: 'All difficulty levels',
};

export const ICONS = {
  LEVELS: 'levels',
  ABOUT: 'about',
  TAG: 'tag',
  TOPICS: 'topics',
  CODE: 'code',
  REACT_LOGO: 'react',
  ARROW_RIGHT: 'arrow-right',
  ARROW_BACK: 'arrow-back',
  TIME: 'time',
  DATE: 'date',
  LEVEL_0: 'Level-0',
  LEVEL_1: 'Level-1',
  LEVEL_2: 'Level-2',
  LEVEL_3: 'Level-3',
  LEVEL_4: 'Level-4',
  LEVEL_5: 'Level-5',
};
